image: node:8.12.0

stages: 
  - deploy

deploy:
  stage: deploy
  script:
    - git remote add heroku:$HEROKU_API_KEY@git.heroku.com/naivebayes8912.git
    - git push heroku master --force

  only:
    - master